source 'http://rubygems.org'

gem 'dotenv'
gem 'fastimage'

gem 'middleman-blog-similar', '2.0.1'
gem "middleman-favicon-maker", '~> 4.1'
gem 'middleman', '4.3.7'
gem 'middleman-blog', '4.0.3'
gem 'middleman-disqus', '1.2.0'
gem 'middleman-google-analytics', '3.0.0'
gem 'middleman-livereload', '3.4.6'
gem 'middleman-ogp', git: 'https://github.com/ngs/middleman-ogp.git', branch: 'asset-hash'
gem 'middleman-syntax', git: 'https://github.com/middleman/middleman-syntax.git', branch: 'master'
gem 'middleman-sprockets'

gem 'redcarpet'
gem 'nokogiri'

gem 'builder', '~> 3.0'
gem 'jbuilder'
gem 'tilt-jbuilder'
gem 'sanitize'

gem 'slim'
gem 'sass'
gem 'coffee-script'
gem 'opal', '~> 0.10.5'
gem 'natto'
gem 'tzinfo-data'
gem 'sqlite3', '~> 1.3.6'
