version: 2.1

orbs:
  ruby: sue445/ruby-orbs@1.3.10

executors:
  main:
    working_directory: ~/src
    docker:
      - image: atsnngs/middleman-blog:latest
    environment:
      BUILD_DIR: build
      TZ: Asia/Tokyo

jobs:
  build:
    executor: main
    parameters:
      lang:
        type: enum
        enum: [en, ja]
    environment:
      MM_LANG: << parameters.lang >>
    steps:
      - checkout
      - ruby/bundle-install
      - run:
          name: Build middleman blog
          command: bundle exec middleman build --verbose --no-parallel
      - run: tar cvfz build.tar.gz build
      - store_artifacts:
          path: build.tar.gz
      - store_artifacts:
          path: .similar.db
          destination: similar.db
      - persist_to_workspace:
          root: ~/src
          paths:
            - build
            - .circleci

  deploy:
    executor: main
    parameters:
      cname:
        type: enum
        enum: [ngs.io, ja.ngs.io]
    environment:
      CNAME: << parameters.cname >>
    steps:
      - attach_workspace:
          at: ~/src
      - run: .circleci/set-git-user.sh
      - run: .circleci/deploy.sh
      - run: .circleci/purge-cloudflare-cache.sh

workflows:
  en:
    jobs:
      - build:
          lang: en
          filters:
            branches:
              only: [master]
      - deploy:
          cname: ngs.io
          requires: [build]
  ja:
    jobs:
      - build:
          lang: ja
          filters:
            branches:
              only: [master]
      - deploy:
          cname: ja.ngs.io
          requires: [build]
