version: 2.1

orbs:
  ruby: sue445/ruby-orbs@1.3.10

executors:
  main:
    working_directory: ~/src
    docker:
      - image: atsnngs/middleman-blog:latest
    parameters:
      lang:
        type: enum
        enum: [en, ja]
      cname:
        type: enum
        enum: [ngs.io, ja.ngs.io]
    environment:
      MM_LANG: << parameters.lang >>
      BUILD_DIR: build
      CNAME: << parameters.cname >>
      TZ: Asia/Tokyo

jobs:
  build:
    executor: << parameters.executor >>
    parameters:
      executor:
        type: executor
    steps:
      - checkout
      - ruby/bundle-install

      - run:
          name: Build middleman blog
          command: bundle exec middleman build --verbose --no-parallel

      - run: tar cvfz build.tar.gz build

      - store_artifacts:
          path: build.tar.gz

      - store_artifacts:
          path: .similar.db
          destination: similar.db

      - persist_to_workspace:
          root: ~/src
          paths:
            - build
            - .circleci

  deploy:
    executor: << parameters.executor >>
    parameters:
      executor:
        type: executor
    steps:
      - attach_workspace:
          at: ~/src
      - run: .circleci/set-git-user.sh
      - run: .circleci/deploy.sh
      - run: .circleci/purge-cloudflare-cache.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          name: build-ja
          executor:
            lang: ja
            cname: ja.ngs.io
            name: main
          filters:
            branches:
              only: master
      - build:
          name: build-en
          executor:
            lang: en
            cname: ngs.io
            name: main
          filters:
            branches:
              only: [master, ci]
      - deploy:
          name: deploy-ja
          executor:
            lang: ja
            cname: ja.ngs.io
            name: main
          requires:
            - build-ja
      - deploy:
          name: deploy-en
          executor:
            lang: en
            cname: ngs.io
            name: main
          requires:
            - build-en
